routes:
    get: 
        "/country/${id}":
            success: true
            id: ${id}
            numero: ${random.integer}
            name: ${random.personLastName}
            request: 
                body: ${request.payload}
                params: ${request.params}
        "/country":
            - $length$: ${random.integer.10}
              id: ${random.integer.200}
              numero: ${random.integer}
              name: ${random.city}
              request: 
                  body: ${request.payload}
                  params: ${request.params}
