$defaultResponse$:
  success: true
  request:
    path: ${request.path} 
    body: ${request.payload}
    params: ${request.params}
$error$:
  $httpStatus$: 500
  success: false
  error: "Error occurred for request: ${request.path}"
  request:
    body: ${request.payload}
    params: ${request.params}
routes:
  "*": 
    "*":
      success: true 
      request: 
        path: ${request.path}         
        params: ${request.params}
