$defaultResponse$:
    success: true
    request: 
        body: ${request.payload}
        params: ${request.params}
$error$:
    $httpStatus$: 500
    success: false
    error: "Error occurred for request: ${request.path}"
    request: $request
routes:
    post: 
        ".*":
            success: true            
            request: 
                body: ${request.payload}
                params: ${request.params}
