name: Upload coverage data to codecov.io
on:
  push:
    branches:
      - main
jobs:
  test-coverage:
    uses: ./.github/workflows/qa-coverage.yml

  upload-codecov:
    runs-on: ubuntu-latest
    needs: test-coverage
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN} 
      - run: echo "🍏 This job's status is ${{ job.status }}."
