name: RELEASE
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v[0-9]+.[0-9]+.?[0-9]*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  test:
    uses: ./.github/workflows/qa-coverage.yml
  build:
    uses: ./.github/workflows/build.yml
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: Variables
        run: |
              echo "APP_VERSION=v${{needs.build.outputs.app_version}}" >> $GITHUB_ENV
              echo "APP_NAME=${{needs.build.outputs.APP_NAME}}" >> $GITHUB_ENV
      - name: Variables
        run: |
              echo "${{ github.ref_name }} != ${{ env.APP_VERSION }}"
      - name: Version Check
        if: ${{ github.ref_name != env.APP_VERSION }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('App version in tag mismatch real code version!!! (${{ env.APP_VERSION }} != ${{ github.ref_name }})')
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false