name: "Docker image: Generate and upload to hub.docker.com"
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    uses: ./.github/workflows/qa-coverage.yml
    
  upload-dockerhub:
    runs-on: ubuntu-latest
    needs: build-and-test
    env:
      DOCKER_ID: dvlprtech
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_ID }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    
      - run: "APP_VERSION=$(npm run --silent version) >> $GITHUB_ENV"
      - run: "APP_NAME=$(npm -p 'require(\'package.json\').name') >> $GITHUB_ENV"
      - run: "DOCKER_IMAGE=${{ env.DOCKER_ID }}/${{env.APP_NAME}} >> $GITHUB_ENV"
      - run: "echo App ${{ env.DOCKER_IMAGE }}"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: ${{ env.DOCKER_IMAGE }}:${{env.APP_NAME}}  ${{ env.DOCKER_IMAGE }}:latest
      - run: echo "🍏 This job's status is ${{ job.status }}."

